name = "OxygenTrial"
uuid = "5124a3bb-fc65-490b-b96a-7f01b8eecbce"
authors = ["John Unwin <john@fingertip.co.nz> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
