name = "OxygenTrial"
uuid = "5124a3bb-fc65-490b-b96a-7f01b8eecbce"
authors = ["John Unwin <john@fingertip.co.nz> and contributors"]
version = "1.0.0-DEV"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"

[compat]
Aqua = "0.8"
HTTP = "1.10"
Oxygen = "1.5"
Test = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
